"""empty message

Revision ID: 9781d5426a10
Revises: 2d25f496e3a1
Create Date: 2019-12-12 14:43:50.733493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9781d5426a10'
down_revision = '2d25f496e3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'description')
    # ### end Alembic commands ###
